[build]
  publish = "dist/client/"
  command = "npm run build:ssr"

[functions]
  directory = "dist/server"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
